CREATE TABLE myweb_user
(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
user_type TINYINT(2) NOT NULL DEFAULT 1 COMMENT '用户类型 0管理员 1普通用户',
user_name VARCHAR(64) NOT NULL DEFAULT '' COMMENT '用户名称',
user_email VARCHAR(128) NOT NULL DEFAULT '' COMMENT 'email',
image VARCHAR(256) NOT NULL DEFAULT '' COMMENT '用户头像',
description VARCHAR(256) NOT NULL DEFAULT '' COMMENT '用户注释',
create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间'
);

CREATE TABLE myweb_posts
(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
post_author INT NOT NULL DEFAULT 0 COMMENT '作者',
post_title VARCHAR(1024) NOT NULL DEFAULT '',
post_status TINYINT(2) NOT NULL DEFAULT 0 COMMENT '0未发布 1已发布 2删除',
post_content TEXT,
comment_count INT NOT NULL DEFAULT 0 COMMENT '回复数',
create_time TIMESTAMP NOT NULL DEFAULT 0 COMMENT '创建时间',
update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP  ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
);

CREATE TABLE myweb_comments
(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
comment_author INT NOT NULL DEFAULT 0 COMMENT '作者',
comment_status TINYINT(2) NOT NULL DEFAULT 1 COMMENT '1已发布 2删除',
comment_post_id INT NOT NULL DEFAULT 0,
coment_author_ip VARCHAR(100) NOT NULL DEFAULT '',
comment_content MEDIUMTEXT,
create_time TIMESTAMP NOT NULL DEFAULT 0 COMMENT '创建时间',
update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP  ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
);


